on:
    push:
      branches:
        - main
    workflow_dispatch:
    
jobs:
    run_pull:
      name: git sync on remote server
      runs-on: ubuntu-latest
      
      steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and run sync
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "~/gitsync.sh --key=\"${{ secrets.SSH_PRIVATE_KEY }}\" --git=git@github.com:${{ github.repository_owner }}/${{ github.event.repository.name }}.git --dir=${{ secrets.DEPLOY_DIRECTORY }} --b=${{ secrets.DEPLOY_BRANCH }}"
      - name: cleanup
        run: rm -rf ~/.ssh
  